### ISSUE TITLE
Edit form in main skills component doesn't work correctly

### ISSUE THREAD

**Issue by NikGurev** [LT-Students/DigitalOffice-frontend#82]
During the editing process input saves current value and change employee info, even if the cancel button was pushed.

![image](https://user-images.githubusercontent.com/42917304/113669531-943d5e80-96bc-11eb-8908-b0c4cfbb4f51.png)

![image](https://user-images.githubusercontent.com/42917304/113669574-a0292080-96bc-11eb-9f49-6beac973bb18.png)

![image](https://user-images.githubusercontent.com/42917304/113669604-aa4b1f00-96bc-11eb-9fc9-5211ea3714eb.png)

**Comment by NikGurev** [comment]
Думаю, нужно всё-таки разделять input и простой текст.
Всю логику формы нужно оставить в компоненте, не выносить в отдельный мини компонент. Хотя лучше почитать статейки, как с этим лучше быть. 
С одной стороны, мне нравится, что мы пишем один компонент и все. А с другой - в каждом компоненте у нас зависимость директивы FormGroupDirective
Я в skills компоненте сделал так: отдельный ng-template формы, а отдельно верстка блок. Соответственно, когда мы меняем режим на edit, то у нас отображается форма, а вся логика в классе компонента

**Comment by tsinevik** [comment]
Т.е. ты предлагаешь вообще убрать подобные мини-компоненты?
У нас же в макетах есть много типовых полей лэйбл+инпут и, мне кажется, удобно, когда есть подобные заранее прописанные компоненты со всеми нужными стилями. Иначе же получается, что каждый раз придется дублировать примерно одни и те же шаблоны и стили для них из компонента в компонент, где встречаются подобные поля. Хотя в случае нестандартного поля с какими-нибудь доп иконками, как было с паролем в new-employee, всё равно пришлось по сути дублировать компонент инпут, но с небольшими дополнениями. Короче, наверное, было бы прикольно иметь что-то, что позволяло бы сократить это дублирование.

Ну и если удалить сами компоненты, то тогда их шаблоны надо по сути просто перенести в ng-template'ы в employee-info? Например, шаблон do-input перенести в условный <ng-template #input>?

**Comment by NikGurev** [comment]
Да, понимаю, выглядит удобно, но работать с этим становится тяжелее - у нас в каждом экземпляра такого компонента появляется новая зависимость в форме FormGroupDirective, что мне не очень нравится.

**Comment by NikGurev** [comment]
Надо подумать над этим

**Comment by NikGurev** [comment]
Давай у Егора спросим в четверг

**Comment by NikGurev** [comment]
@tsinevik проблема еще это подхода в том, что выводимое значение напрямую зависит от control.value. Соответственно, когда нам нужно очистить форму, то все сведения исчезают, из-за чего возникает баг.

Твоя идея мне нравится, нужно будет её хорошо продумать

**Comment by NikGurev** [comment]
@tsinevik я займусь этой задачей пока что

**Comment by NikGurev** [comment]
@tsinevik  https://github.com/LT-Students/DigitalOffice-frontend/pull/84
